### ISSUE TITLE
RS_Reports: Application fatal error for a particular DB while generating Polar Plot and Polar Plot time base report

### ISSUE THREAD

**Issue by boopeshwar** [boopeshwar/TestRepo#6]
The application gets a fatal error when user performs below operation:
Select the DB - Enb10301
Click Full Reporting
Click Polar Plot Time Base under Time Base.

The fatal error shown as below:
![image](https://cloud.githubusercontent.com/assets/20275332/16873718/97ce8c32-4ab2-11e6-8716-9dc8d0ac2fd3.png)

The same operation works fine for other DB file such as - TIR11101

**Comment by boopeshwar** [comment]
If the DB does not contain the necessary values for the report, the application shall display an Alert message instead of Fatal error.

**Comment by klakshmanan** [comment]
Issue has been fixed by changing "Single" to "SingleOrDefault" in the Linq query and checked plots value not equal to null before plotting.

![image](https://cloud.githubusercontent.com/assets/21661266/18504429/de5f2506-7a7f-11e6-805d-28e0bf231b4e.png)

**Comment by boopeshwar** [comment]
Issue has been verified and reports were generated without fatal error.
